### ISSUE TITLE
opentype-shaping-arabic.md vs. opentype-shaping-arabic-general.md 

### ISSUE THREAD

**Issue by bobh0303** [n8willis/opentype-shaping-documents#137]
I'm trying to figure out the relationship between [opentype-shaping-arabic.md](https://github.com/n8willis/opentype-shaping-documents/blob/master/opentype-shaping-arabic.md) and [opentype-shaping-arabic-general.md](https://github.com/n8willis/opentype-shaping-documents/blob/master/opentype-shaping-arabic-general.md) as they both have a lot of the same material. Is there guidance on which to use when?

**Comment by n8willis** [comment]
Hi Bob; thanks for the question.

Short answer is that "general" is the top-level document that provides an overview where a single model gets shared by more than one specific script. With the Arabic model, that's a bit confusing perhaps, because of the shared term, but we don't really have a more apropos name for the general one that's shared by Arabic, Syriac, N'Ko, and Mongolian.... So you start with general, then you work your way through the specific scripts. It's analogous to how the "Indic" model applies to a larger set of scripts because of their orthographic relationships. 

I would also add that the top-level README doc in the repository attempts to provide an answer to this question, by pointing people to the "general" documents and not to the particular-to-one-script docs (with those links being contained in the "general" documents themselves).

Admittedly, the GitHub page layout pushes the contents of README well below the file list, but of course that's not really something they leave up to us mere users. 

However, if you have a wording change to suggest for the README file that you think might make those inter-document relationships clearer, definitely please do say so!

**Comment by n8willis** [comment]
Gonna go ahead and close this since there is "an answer" for how the docs relates. Please feel free to open a more precise issue or PR regarding the details of the wording if you like, though.
