### ISSUE TITLE
Tagging Bengali below-base consonants

### ISSUE THREAD

**Issue by adrianwong** [n8willis/opentype-shaping-documents#41]
Consider the sequence "Ka, Halant, Ba, U" (`U+0995`, `U+09CD`, `U+09AC`, `U+09C1`). Based on our tagging rules:

* "Ka" == `POS_BASE_CONSONANT`
* "U" == `POS_AFTER_SUBJOINED` (as it is a below-base dependent vowel)

What should the tag for "Ba" be? It's a codepoint that has a below-base _form_, but is in post-base _position_.

If we tag it as `POS_POSTBASE_CONSONANT` (i.e. by position relative to the base) (related issue: #38), the initial reorder results in "Ka, U, Halant, Ba" (the dependent vowel moves in front of the consonant, as `POS_AFTER_SUBJOINED` < `POS_POSTBASE_CONSONANT`). This gives us:

![screen shot 2018-12-06 at 4 22 29 pm](https://user-images.githubusercontent.com/8623831/49563252-3923c180-f973-11e8-9c41-1021062b65e0.png)

If we tag it as `POS_BELOWBASE_CONSONANT`, we get the correct behaviour:

![screen shot 2018-12-06 at 4 25 49 pm](https://user-images.githubusercontent.com/8623831/49563348-a5062a00-f973-11e8-8cb1-b2b095cb01a7.png)

The Bengali spec doesn't currently cover the tagging of `POS_BELOWBASE_CONSONANT`s.

**Comment by n8willis** [comment]
`POS_BELOWBASE_CONSONANT` and `POS_POSTBASE_CONSONANT` (as well as the 'above' and 'pre' variants) aren't about the original position of the consonant in the syllable, they're about whether the character gets a GSUB feature applied (`blwf`, etc.). (After all, because the sorting happens, the original positions of some characters will be lost anyway.)

Bengali Ba should be `POS_BELOWBASE_CONSONANT`. I guess the spec is silent on when you'd tag it because it defers to the implementor on how to decide whether it ought to tag. That was the purpose of:

> For example, one implementation may choose to maintain a static table of below-base and post-base consonants to compare again the text run. Another implementation might examine the active font to see if it includes a relevant blwf or pstf lookup in the GSUB table.

at the end of 2.1. Probably all existing implementations look in GSUB; HarfBuzz certainly does. We could just add it there. (IMO, the predefined table approach would be slightly faster perhaps, but cause problems tagging things when the font doesn't actually implement the feature...)

**Comment by adrianwong** [comment]
> `POS_BELOWBASE_CONSONANT` and `POS_POSTBASE_CONSONANT` (as well as the 'above' and 'pre' variants) aren't about the original position of the consonant in the syllable, they're about whether the character gets a GSUB feature applied (`blwf`, etc.). (After all, because the sorting happens, the original positions of some characters will be lost anyway.)

Gotcha, thanks.

> Bengali Ba should be `POS_BELOWBASE_CONSONANT`. I guess the spec is silent on when you'd tag it because it defers to the implementor on how to decide whether it ought to tag. That was the purpose of:
>
> > For example, one implementation may choose to maintain a static table of below-base and post-base consonants to compare again the text run. Another implementation might examine the active font to see if it includes a relevant `blwf` or `pstf` lookup in the GSUB table.

But why do we also have step 2.7 then, if it's up to the implementor how they'd like to handle `pstf`?

**Comment by n8willis** [comment]
> But why do we also have step 2.7 then, if it's up to the implementor how they'd like to handle pstf?

I'm interpreting a tiny bit, but I think that's the way HarfBuzz does it because POST- and PRE- consonant types are almost always spacing letters. So if you forgot to handle them entirely, you'd have all sorts of trouble with your advances and overall horizontal length. Whereas the BELOW- consonant type is going to get mark positioning.

Also, I probably ought to clarify that the thing that's up to the implementor is "how do I decide which consonants to skip when searching for the base consonant", not "what do I do with POST and BELOW consonants" in general.

Circling back to the original issue, it sounds like two changes are in order:
 - be more explicit in 2.1 about the reasons and approaches for knowing what consonants to skip during the base search
 - add an explicit 'tag them here' instruction for BELOW (or at least a 'tagging them here is a good idea because ___' that can be a catch-all)

Agree? Something else?

**Comment by adrianwong** [comment]
Sounds good! I think it might be nice to have some concrete examples to go with the first point.

If you're happy for me to help out, I have some examples from the Siyam Rupali font that you may be able to use.

**Comment by n8willis** [comment]
Upon further reflection, I think that the simplest change to understand (and, by coincidence, to make) is to expand on the "skip consonants" bullet-points in the base-search algorithm in 2.1, and tag the things that are getting skipped as they're encountered.

In other words:

- Starting from the end of the syllable, move backwards until a consonant is found.
    - If the consonant has a below-base form, tag it as POS_BELOWBASE_CONSONANT, then move to the previous consonant. 
    - If the consonant has a post-base form, tag it as POS_POSTBASE_CONSONANT, then move to the previous consonant. 
    - If the consonant is a pre-base-reordering "Ra", tag it as POS_RA_TO_BECOME_REPH, then move to the previous consonant. 
    - If none of the above conditions is true, stop.
    - If the consonant is the first consonant, stop.

We would still leave in the note about how you determine which consonants have a special form, since that could still be done via GSUB inspection or by using Unicode info.

I have this in a Bengali update that I'm rereading before commit. May break it out into a separate commit to speed things along. The main question is: does that leave any considerations un-dealt-with?

**Comment by adrianwong** [comment]
I like it! I think it makes things clearer for the implementer.

Two points for discussion:

* If this change is incorporated, does this mean we can do away with [section 2.7](https://github.com/n8willis/opentype-shaping-documents/blob/master/opentype-shaping-indic-general.md#27-post-base-consonants) altogether? I raised an issue (#38) where I (very poorly) described my finding that post-base consonants do not necessarily have to occur after a matra to be tagged as such. This change and removing 2.7 resolves two issues in one fell swoop!
* We currently use `POS_RA_TO_BECOME_REPH` for tagging syllable-initial "Ra, Halant, (+ZWJ for Telugu/Sinhala)" sequences. I think it's just [Malayalam](https://github.com/n8willis/opentype-shaping-documents/blob/master/opentype-shaping-malayalam.md#44-pre-base-reordering-consonants) that has the notion of a pre-base-reordering "Ra", and the existing [section 2.7](https://github.com/n8willis/opentype-shaping-documents/blob/master/opentype-shaping-malayalam.md#27-post-base-consonants) mentions that it should be tagged with `POS_POSTBASE_CONSONANT` for consistency. Given that it's a post-base-positioned consonant, but is reordered to pre-base-position and takes on a pre-base form, should we tag it with `POS_PREBASE_CONSONANT` instead? Just throwing out ideas here - I don't know what would be considered more "correct" in this context.

**Comment by n8willis** [comment]
> If this change is incorporated, does this mean we can do away with [section 2.7](https://github.com/n8willis/opentype-shaping-documents/blob/master/opentype-shaping-indic-general.md#27-post-base-consonants) altogether?

I think no, and that instead that 2.7 really ought to be for tagging POS_FINAL_CONSONANT. Probably it reflects initial confusion on my part between the two, especially since I started with Bengali and did not get to Sinhala until last. I want to look at a couple more fonts before I feel 100% on that, though.

> I think it's just [Malayalam](https://github.com/n8willis/opentype-shaping-documents/blob/master/opentype-shaping-malayalam.md#44-pre-base-reordering-consonants) that has the notion of a pre-base-reordering "Ra", 

Currently, yes -- for the Indic2 shaping model. At least for the primary languages (an increasingly common caveat, I notice...). It is also done in Khmer & Myanmar, at least, and there are valid reasons to try and keep the "Other Brahmic" models in the same general pattern. Like the fact that USE is a generalization of Indic2, and people might decide to migrate their Brahmic or Indic2 scripts to USE in the future.

> and the existing [section 2.7](https://github.com/n8willis/opentype-shaping-documents/blob/master/opentype-shaping-malayalam.md#27-post-base-consonants) mentions that it should be tagged with `POS_POSTBASE_CONSONANT` for consistency. Given that it's a post-base-positioned consonant, but is reordered to pre-base-position and takes on a pre-base form, should we tag it with `POS_PREBASE_CONSONANT` instead? Just throwing out ideas here - I don't know what would be considered more "correct" in this context.

Here, too, I want to dig through a few more fonts. But I think that HarfBuzz tags it as _POSTBASE_ for a reason.... If nothing else, it would keep it from getting sorted in adjacent to other PREBASE consonants that will stay PREBASE, and potentially get in the way of ligature/etc GSUBs aimed at those.

**Comment by n8willis** [comment]
OK; further reflection again.

- 2.7 : this is, indeed, for POSTBASE CONSONANTs; I need to also include a mention of FINAL_CONSONANTs (including that only Sinhala uses them). At issue is preserving things that have a special postbase form but do not get reordered, like mlm2 Va and Ya.

 - Malaylam pre-base-reordering Ra : HarfBuzz tags these in the same manner that it tags POSTBASE and BELOWBASE and FINAL, by inspecting the BLWF and PSTF substitutions (etc) in GSUB. Consequently, because most fonts in the wild make the glyph substitution for pre-base-reordering Ra *before* doing the actual final reordering step, they evidently tend to use GSUB rules that include the Ra (pre-base-reordering) and both the Ya and Va (which remain postbase) in one lookup. The reordering of the Ra much later in 4.4 does that by knowing that the Ra codepoint gets reordered; it doesn't care about the GSUB substitution anymore (that's ancient history).

For sorting purposes, as we're doing in 2.n, it's important that the pre-base-reordering Ra in mlm2 not get reordered too early; fonts expected it to not get reordered until 4.4. It it got reordered in the initial-reordering sort, that would likely break GSUB lookup patterns.

**Comment by adrianwong** [comment]
> For sorting purposes, as we're doing in 2.n, it's important that the pre-base-reordering Ra in mlm2 not get reordered too early; fonts expected it to not get reordered until 4.4. It it got reordered in the initial-reordering sort, that would likely break GSUB lookup patterns.

Right! That makes sense.

**Comment by n8willis** [comment]
Okay; one additional rethink. IF we redesign the base-consonant search algorithm so that we also tag special-form consonants while we are searching backward, THEN 2.7 only needs to worry about POS_FINAL (and, then, only for Sinhala in the current set, AFAIK). As long as we want to maintain the Grand Unified Indic model, 2.7 will need to stick around, but you're right in that nothing POS_POSTBASE be would left uncaught if we tagged it during the backward-search step.

**Comment by n8willis** [comment]
In addition, I think that 2.5 needs an update to indicate that below-base forms can be encountered before the base as well (thanks to BLWF_MODE_PRE_AND_POST).

**Comment by adrianwong** [comment]
> Okay; one additional rethink. IF we redesign the base-consonant search algorithm so that we also tag special-form consonants while we are searching backward, THEN 2.7 only needs to worry about POS_FINAL (and, then, only for Sinhala in the current set, AFAIK). As long as we want to maintain the Grand Unified Indic model, 2.7 will need to stick around, but you're right in that nothing POS_POSTBASE be would left uncaught if we tagged it during the backward-search step.

> In addition, I think that 2.5 needs an update to indicate that below-base forms can be encountered before the base as well (thanks to BLWF_MODE_PRE_AND_POST), which would close #44. That should be straightforward.

Both seem like sound changes! Thanks for your good work!

**Comment by n8willis** [comment]
Pushed 9ef09bb, propagating the revised language from Bengali to all non-SInhala Indic scripts. I believe this should take care of this issue as well as the related ones mentioned above. Do take a peek and let me know how it reads, however, before I close it.

**Comment by adrianwong** [comment]
Awesome stuff @n8willis! I think it reads really well!

I've noticed two issues in this paragraph (emphasis mine):

> Note: Shaping engines may choose any method to identify consonants that
> have below-base or post-base forms while executing the above
> algorithm. For example, one implementation may choose to maintain a
> static table of below-base and post-base consonants to compare **again**
> the text run. Another implementation might examine the active font
> to see if it includes a `blwf` or `pstf` lookup in the GSUB table
> that affects the consonants encountered in the syllable.

1. "again" should be "against". **
2. This paragraph (as it is used in section 2.1 at least) should also mention pre-base-reordering "Ra" form and the `pref` lookup.

** Are there shaping engines currently in (wide) use that take the approach of maintaining a static table of consonants? Should we do away with the first half of that paragraph and just state that the font should be inspected for the lookup, or would that be overly prescriptive?

**Comment by adrianwong** [comment]
> ** Are there shaping engines currently in (wide) use that take the approach of maintaining a static table of consonants? Should we do away with the first half of that paragraph and just state that the font should be inspected for the lookup, or would that be overly prescriptive?

Argh, sorry, I just realised that you've already touched on this in some earlier posts in this thread:

> Probably all existing implementations look in GSUB; HarfBuzz certainly does.

> We would still leave in the note about how you determine which consonants have a special form, since that could still be done via GSUB inspection or by using Unicode info.

I suppose the question still stands - has GSUB inspection become the de-facto approach?

**Comment by n8willis** [comment]
The more I think about this, the more I'm inclined to say it doesn't matter if there are shaping engines that _don't_ inspect GSUB. After all, this is intended to be a description of OpenType Shaping; we'd might as well say that "inspecting GSUB is the only way to know for certain if a letter in the active font has a special form" and leave it to a 'special note' that you can go another way if you're willing to take the risks.

The lingering little bit of trickiness (I mean, we'll never really know what Uniscribe and CoreText do under the hood) is that USE advises doing things by way of Unicode properties in several key stages. But, for practical purposes, that may mean more that we ought to be concerned about future OT shapers trying to support Indic inside their USE engine. Hypothetically possible, but where it will fail is all the existing fonts that do their own GSUB stuff and don't pay strict adherence to Unicode properties.

So I guess I'm suggesting taking a 'soft stand' on this: we could say that the shaper has to know if characters take on special forms and say that inspecting GSUB is the "correct" way to check.

**Comment by n8willis** [comment]
@adrianwong How does that sound?

**Comment by adrianwong** [comment]
> @adrianwong How does that sound?

> So I guess I'm suggesting taking a 'soft stand' on this: we could say that the shaper has to know if characters take on special forms and say that inspecting GSUB is the "correct" way to check.

Apologies for the delayed response - sounds good to me!

**Comment by n8willis** [comment]
OK. Pushed out with 9d0eba3 ... other cleanup from preceding comment as well.

Ultimately, added a full paragraph right after the stage-1 discussion that introduces special forms, and a briefer note to the 2.1 and 2.5 steps where tagging `blwf`/`pstf`/`pref` happens.

**Comment by adrianwong** [comment]
Thanks heaps @n8willis - the changes read well!
