### ISSUE TITLE
[Gurmukhi] `akhn` substitution feature

### ISSUE THREAD

**Issue by adrianwong** [n8willis/opentype-shaping-documents#49]
Gurmukhi doesn't have a "[Ssa](https://unicode.org/charts/PDF/U0A00.pdf)" consonant, so the "Ka, Halant, Ssa" sequence in [section 3.3](https://github.com/n8willis/opentype-shaping-documents/blob/master/opentype-shaping-gurmukhi.md#33-akhn) shouldn't be possible.

**Comment by n8willis** [comment]
True, but it has been proposed, though ( http://unicode.org/L2/L2006/06233-gurmukhi.pdf ), and evidently some people write it with a nukta on Sa. 

It's clear (from Unicode and elsewhere) that _Punjabi_ doesn't use akhands and other ligature-like conjuncts, but that doesn't necessarily mean that minority languages wouldn't ever do it. I find a lot of "minority language X uses this" to be the answer when I ask about things on the HarfBuzz list. That's why we started adding the "$FEATURE is rare in this script" note, rather than saying that something "never" or "cannot" happen.

**Comment by n8willis** [comment]
I mean, if someone created a Gurmukhi font that included an akhn feature intending to support a minority language, I don't think it would violate the MS spec and the user would likely expect that the feature would be applied like it would be in a different script, don't you think?

**Comment by adrianwong** [comment]
> I mean, if someone created a Gurmukhi font that included an akhn feature intending to support a minority language, I don't think it would violate the MS spec and the user would likely expect that the feature would be applied like it would be in a different script, don't you think?

Agreed, and thanks for the explanation!

We don't specifically disable AKHN features for Gurmukhi, so this doesn't affect our implementation in any way. I raised this issue just in case this may be a copy/paste error, which clearly it isn't.

Closing this as a non-issue.
