### ISSUE TITLE
Telugu Reph

### ISSUE THREAD

**Issue by adrianwong** [n8willis/opentype-shaping-documents#56]
[Section 3.4](https://github.com/n8willis/opentype-shaping-documents/blob/master/opentype-shaping-telugu.md#34-rphf) should state that initial "Ra, Halant, **ZWJ**" sequences be replaced with the "Reph" glyph, given that Telugu has the `REPH_MODE_EXPLICIT` characteristic.

**Comment by n8willis** [comment]
Fixed by 22469cb.

**Comment by lianghai** [comment]
According to what the _Core Spec_ 12.0’s section “Reph” (page 500, 12.7 _Telugu_) currently specifies, formation of repha is at the discretion of fonts. Thus it’s not a typical `REPH_MODE_EXPLICIT` case?

- Explicit repha in modern texts/fonts that otherwise do not use repha: <ra, virama, ZWJ>
- Repha in older-style texts/fonts: <ra, virama>

**Comment by adrianwong** [comment]
Thanks @lianghai. So (by our categorisation) older Telugu would really be `REPH_MODE_IMPLICIT`.

My initial (and hazy) thoughts about how a shaping engine would support old and new Telugu would be to dynamically assign a `REPH_MODE` to Telugu input based on inspecting a font's `rphf` feature.

I'm also curious about how a shaping engine would handle:

* new font, old text - no repha formation.
* old font, new text -
  * no repha formation, if adhering to the [OpenType spec](https://docs.microsoft.com/en-us/typography/script-development/telugu#effect-of-zwj-zwnj-and-nbsp-on-consonant-shaping) (i.e. a ZWJ following a <ra, virama> prevents repha formation).
  * repha formation with a lingering ZWJ, if adhering to the Core Spec (i.e. <ra, ZWJ, virama> prevents repha formation).
