### ISSUE TITLE
[Indic] Kannada "Ra, Halant, ZWJ" legacy behaviour

### ISSUE THREAD

**Issue by adrianwong** [n8willis/opentype-shaping-documents#61]
It appears that to be compatible with legacy Kannada, a "Ra, Halant, ZWJ" sequence should behave like "Ra, ZWJ, Halant". There is a bit more of a discussion [here](https://github.com/harfbuzz/harfbuzz/issues/435).

Should this be formalised in the Kannada shaping spec?

**Comment by n8willis** [comment]
Based on that discussion, it seems like the underlying issue is a toss-up between something we would categorize as an "Indic1 compat" recommendation (since it's documented at Unicode) and something for errata (because of the ambiguity factor). I'd be inclined to say that it ought to go in compat, since it's evidently been for so many years, but when we started that section we weren't tracking errata at all. If you're persuaded of compat, I'll put it there.

**Comment by adrianwong** [comment]
Agreed - it should probably go in compat.

**Comment by n8willis** [comment]
Okay; patched in 5c7e0b3. Because this seems to be an Indic1-era–only concern and it's Unicode-oriented, it is noted in the Kannada doc's `<knda>` treatment section, rather than (say) in the Uniscribe-compatibility notes.
