### ISSUE TITLE
[Indic] Pre-base matra reordering exceptions for Malayalam and Tamil

### ISSUE THREAD

**Issue by adrianwong** [n8willis/opentype-shaping-documents#68]
Malayalam "Consonant, Halant, ZWJ" sequences form Chillus; Tamil "Consonant, Halant, ZWJ" sequences form _ligated_ explicit Halant forms.

There should be a note in both specifications to say that pre-base matras should be moved after these glyphs.

**Comment by lianghai** [comment]
> There should be a note in both specifications to say that pre-base matras should be moved after these glyphs.

Yes, for chillus, because they’re usually written syllables on their own (except when they’re combined with following consonant signs…).

But what is a Tamil “_ligated_ explicit Halant form” though? How is a halant form ligated, ?

**Comment by adrianwong** [comment]
> But what is a Tamil “ligated explicit Halant form” though? How is a halant form ligated?

My understanding is that pre-base Tamil "Consonant, Halant, (ZWJ)" sequences can be ligated to form a composite glyph that, in appearance, is no different than if the sequence wasn't ligated. This occurs in some of the Tamil fonts we've tested against.

Relevant HarfBuzz comment can be found [here](https://github.com/harfbuzz/harfbuzz/blob/master/src/hb-ot-shape-complex-indic.cc#L1179-L1182).

**Comment by adrianwong** [comment]
> Although I guess if the ligature is indistinguishable from the unligated form, it might not be too illuminating....

Haha, this is true! Let me try a different approach...

Head over to [this](https://opentype.js.org/glyph-inspector.html) site and load up the latest NotoSansTamil-Regular.ttf font. You'll see that glyphs 77-99 are composite glyphs of glyphs 18-40 with an added Halant (glyph 52), formed via ligature substitution.

**Comment by n8willis** [comment]
Based on @lianghai 's [comment](https://github.com/n8willis/opentype-shaping-documents/issues/73#issuecomment-617792882), it sounds to me like:

1. the intent in Unicode is that the Halant blocks the reordering (as a rule), which in turn means that...

2. for the Tamil case, as noted here, the expectation is that...

3. the font is using ligation for stylistic presentation reasons and the ligature still includes the Halant.

i.e., if the Tamil ligature did _not_ show the visible Halant, then Unicode's R16 would expect the pre-base matra to be to the left of the ligature. (In this case, it being a moot point that the ligature sounds like it's wrong). However, the shaping engine can't actually know if the Tamil ligature involves a visible Halant, since that's potentially a question left up to human eyes.

Therefore, encoding this as a spec rule is drawing on an assumption that fonts are not being pathological.

**Comment by n8willis** [comment]
I believe this to be fixed now through #98. Feel free to reopen if necessary.
