### ISSUE TITLE
[Indic] Pre-base matra reordering with ZWJ

### ISSUE THREAD

**Issue by adrianwong** [n8willis/opentype-shaping-documents#73]
In [section 4.2](https://github.com/n8willis/opentype-shaping-documents/blob/master/opentype-shaping-indic-general.md#42-pre-base-matras) of our spec, we state that a pre-base matra should be moved after a ZWJ/ZWNJ if said joiner/non-joiner follows a "Halant". The [OpenType spec](https://docs.microsoft.com/en-us/typography/script-development/bengali#reorder-characters) agrees with this.

However, the good folk at HarfBuzz have found that statement to be [untrue](https://github.com/harfbuzz/harfbuzz/blob/4f37c0db9bf4e3d536a50126d17b36009b12f9cb/src/hb-ot-shape-complex-indic.cc#L1142-L1168) for ZWJs.

In addition to the Devanagari test case in the code comments, here are some other examples that support the fact that the OpenType spec is likely incorrect:

**Bengali** - Nirmala UI or Noto Sans/Serif Bengali, using a glyph that doesn't possess a half form:

* U+09A5 (Tha), U+09CD (Halant), U+0995 (Ka), U+09BF (Vowel Sign I)

![Screenshot from 2019-06-13 13-43-40](https://user-images.githubusercontent.com/8623831/59402373-571a2500-8de1-11e9-901d-9a286b10aec9.png)

* U+09A5 (Tha), U+09CD (Halant), U+200D (ZWJ), U+0995 (Ka), U+09BF (Vowel Sign I)

![Screenshot from 2019-06-13 13-43-53](https://user-images.githubusercontent.com/8623831/59402378-5aadac00-8de1-11e9-8ac9-bc792fd7446b.png)

**Oriya** - Noto Sans Oriya

* U+0B38 (Sa), U+0B4D (Halant), U+200D (ZWJ), U+0B2A (Pa), U+0B47 (Vowel Sign E)

![Screenshot from 2019-06-13 13-49-55](https://user-images.githubusercontent.com/8623831/59402559-40280280-8de2-11e9-922d-aed6a92ee8c9.png)

On top of the above, Uniscribe does something extra that HarfBuzz doesn't, which is to move a pre-base matra after a "Halant, ZWJ" if the glyph following the ZWJ is a half form.

**Bengali** - Noto Sans/Serif Bengali:

* U+09A5 (Tha), U+09CD (Halant), U+200D (ZWJ), U+09A6 (Da), U+09CD (Halant), U+0995 (Ka), U+09BF (Vowel Sign I)

![zwj-half-uniscribe](https://user-images.githubusercontent.com/8623831/59404628-9b5df300-8dea-11e9-82c3-db89780a4361.PNG)

**Comment by n8willis** [comment]
So, in trying to regularize/clean-up our ZW[N]J treatment, this issue stands out as potentially flagging a spec problem that we ought to document in the errata.

Although the HarfBuzz test case is documented (inline) as a Uniscribe-compatibility thing, the original test case [seems](https://github.com/harfbuzz/harfbuzz/issues/1070) to be an Adobe thing (Adobe Devanagari, "wrservices" which the Googles says is a Photoshop library).

@lianghai do we have any guidance on this from Unicode?

**Comment by lianghai** [comment]
I’m not aware of any prescription from the Unicode Standard regarding ZWJ’s direct effect on reordering.

The Unicode Standard (more or less) specifies that ZWJ is generally used to request the regular conjoining form of a base when the base is together with a virama on the same side of the ZWJ. (Then the formation of the conjoining form naturally affects the sign reordering mechanism.) The standard does not yet have a clear recommendation about whether ZWJ should nonetheless affect reordering when the font is not able to shape the said conjoining form.

Well, the Unicode Standard’s R16 (page 462, _Core Spec_)—

<img width="670" alt="Screen Shot 2020-04-22 at 21 49 06" src="https://user-images.githubusercontent.com/343259/79989995-1865f880-84e3-11ea-8f3a-84ec000bdddc.png">

—actually seems to be pretty explicit about the condition for reordering: as long as the virama is still explicit, the previous akshara should terminate.

Now, I understand the OTL Indic model allows pseudo half forms to be formed in the `half` feature, but letting ZWJ affect reordering without even forming a pseudo half form? This doesn’t sound right. I assume this behavior (that <base, virama, ZWJ> acts as a half form in reordering, regardless of the actual formation of a half form) is some overlooked legacy from Indic 1 (where such properties are very much resolved on the level of character sequences, without consulting the font’s shaping rules).

(This issue is also relevant, right? https://github.com/n8willis/opentype-shaping-documents/issues/68)

**Comment by n8willis** [comment]
So, re-examining this, it seems to me that the OTL script-doc and the Unicode std concur that an explicit virama should stop the matra move and that what HarfBuzz folk discovered is far more in-line with a Uniscribe-compatibility guarantee than it is an assertion that the specification is incorrect.

The "Consonant,halant,ZWJ,halfform,Base" case behaving differently from the "Consonant,halant,ZWJ,Base" case in Uniscribe makes me suspicious that they're just testing separately for half-forms. 

I also don't think the fact that the parenthetical comment in R16 mentions ZWNJ but doesn't mention ZWJ can be taken as prescribing that a ZWJ would (or should) trigger the opposite behavior.

Since HarfBuzz does follow Uniscribe on the ZWJ case by default, however, to my mind that means we must note the discrepancy in the main docs rather than leave it to the Uniscribe-compatibility note.

I've put that into a PR; open for feedback. Only other facet of this that I have lingering concern over is the fact that there are known Uniscribe test cases for so few scripts.

**Comment by n8willis** [comment]
Closed by e514603.
