### ISSUE TITLE
Clarify sources for these documents

### ISSUE THREAD

**Issue by NorbertLindenberg** [n8willis/opentype-shaping-documents#90]
To understand to what extent the documents in this project can be relied on, it would help to know which information sources were used:
– Other documentation, such as Microsoft’s shaping engine documentation?
– Information provided or reviewed by product owners or engineers of the main implementations (HarfBuzz, CoreText, Uniscribe/DirectWrite, Lipika)?
– Inspection of source code of the main implementations?
– Extensive tests run against the main implementations?
– Anything else?

I noticed a few issue comments from Behdad, but that’s all I can see so far...

**Comment by n8willis** [comment]
Quite right. This, like the "project naming" question, is one that we intentionally chose silence on at the beginning, because we weren't sure what direction some things would take along the way (e.g., how closely we would stick to "what HarfBuzz does" when there was an ambiguity in the MS docs or discrepancy between the docs and observed Uniscribe behavior).

I think at this point, I would describe it (succinctly) as "written based on available OpenType Layout documents published by Microsoft plus implementation details in publicly available shaping-engine source code." Probably needs a lengthier description as well, perhaps in the README and pointing to the Uniscribe-compatibility or errata document, which have direct references in them.

**Comment by n8willis** [comment]
Updated the README with source information in c056b91.
