### ISSUE TITLE
Tagging clarifications

### ISSUE THREAD

**Issue by alfiedotwtf** [n8willis/opentype-shaping-documents#97]
> At the end of this process, all letters should be tagged for possible substitution by one of the isol, init, medi, or fina features.

Not sure if that should be `all` or `most`. The pathological case is a word where every glyph has JOINING_TYPE_TRANSPARENT - only the first glyph will be tagged with `isol`, every remaining glyph will skip getting tagged.

**Comment by n8willis** [comment]
Okay, fair enough. I would strongly prefer to avoid using imprecise terms like "most" or "some" when we're describing expected behavior or results, though.

Better to be precise if we can. Would the phrasing "all letters (except those of `JOINING_TYPE_TRANSPARENT`) should be tagged [...]" cover it, do you think?

**Comment by n8willis** [comment]
Also, out of curiosity, are you aware of any such pathological words?

Not that we'd need to put them in the spec, but just for future reference.

**Comment by alfiedotwtf** [comment]
I'm starting to think that no change is needed...

The current text says ```all letters should be tagged ```. 

As diacritics are the glyphs with `JOINING_TYPE_TRANSPARENT` and are not really letters by themselves, I'm guessing we can leave it as is.

As for the pathological words, none exists that I know of. This was just me inspecting the code and looking for where bugs could lurk :)
